"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "ID" | "EN" | "JP" | "ZH" | "RU";
type Theme = "dark" | "light";

interface GlobalState {
    theme: Theme;
    toggleTheme: () => void;
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const dictionaries = {
    ID: {
        "nav.home": "Beranda",
        "nav.about": "Tentang",
        "nav.projects": "Proyek",
        "nav.memories": "Kenangan",
        "nav.dashboard": "Dasbor Vibe",
        "nav.admin": "Konsol Admin",
        "nav.cv": "Curriculum Vitae",
        "nav.contact": "Kontak",
        "hero.role": "IT Data Analyst, Web3 Programmer, Vibe AI Specialist, & Smart Contract Architect.",
        "hero.desc": "Merancang arsitektur data prediktif dan membangun inovasi terdesentralisasi masa depan.",
        "hero.cta": "Jelajahi Karya",
        "about.title": "TENTANG SAYA",
        "about.desc1": "Saya Bagus Priambudi, lulusan S1 Teknik Informatika (Konsentrasi Data Analisis). Saya telah mengembangkan minat yang mendalam pada arsitektur Web3 dan Perdagangan Algoritmik. Visi saya adalah menggabungkan sistem yang aman dengan antarmuka yang sangat indah.",
        "about.desc2": "Saya mengkhususkan diri dalam membangun Dashboard Vibe tingkat lanjut, di mana setiap titik data dirender dengan presisi desain visual yang tiada banding. Saya bukan pendatang baru di ekosistem digital - saya adalah inovator yang selalu ingin belajar.",
        "about.role": "MENGHUBUNGKAN DATA & TEKNOLOGI WEB3",
        "timeline.title": "JURNAL EVOLUSI SAYA",
        "timeline.subtitle": "KLIK KARTU UNTUK DETAIL",
        "timeline.m1.title": "SEKOLAH DASAR & MENENGAH",
        "timeline.m1.label": "FONDASI AWAL LOGIKA",
        "timeline.m1.details": "Membangun ketertarikan awal pada logika, pemecahan masalah (problem solving), dan pola pikir analitis.",
        "timeline.m2.title": "SEKOLAH KEJURUAN (SMK/SMA)",
        "timeline.m2.label": "PEMROGRAMAN DASAR",
        "timeline.m2.details": "Mulai mendalami algoritma, struktur data dasar, serta praktek langsung merakit logika kode.",
        "timeline.m3.title": "PERGURUAN TINGGI (KULIAH)",
        "timeline.m3.label": "ILMU KOMPUTER TINGKAT LANJUT",
        "timeline.m3.details": "Eksplorasi mendalam tentang Arsitektur Basis Data, Rekayasa Perangkat Lunak, dan Jaringan Komputer.",
        "timeline.m4.title": "BOOTCAMP & SERTIFIKASI",
        "timeline.m4.label": "SPESIALISASI WEB3 & AI",
        "timeline.m4.details": "Pelatihan intensif memfokuskan pengerjaan proyek Fullstack Modern, Web3, dan integrasi Artificial Intelligence.",
        "timeline.m5.title": "DUNIA PROFESIONAL",
        "timeline.m5.label": "IMPLEMENTASI DUNIA NYATA",
        "timeline.m5.details": "Terjun penuh ke industri perangkat lunak, mengembangkan sistem berskala besar yang digunakan oleh puluhan ribu klien.",
        "chat.title": "VIBE A.I. AGENT",
        "chat.ready": "AGEN SIAP UNTUK IMPLEMENTASI BACKEND",
        "chat.intro": "Halo! Saya adalah Vibe AI Agent, asisten cerdas pribadi Bagus Priambudi. Ada yang bisa saya bantu terkait Web3, Analisis Data, atau portofolio ini?",
        "chat.command": "Eksekusi perintah...",
        "chat.sim": "[Simulasi]: Saya sedang tidak dihubungkan ke backend oleh Mas Bagus.",
        "dashboard.title": "ARSITEKTUR DEFI",
        "dashboard.role": "ARSITEK KONTRAK PINTAR",
        "dashboard.desc": "Navigasi infrastruktur Web3, menggabungkan keamanan kriptografi ekstrim dengan efisiensi sistem terdesentralisasi. Sinkronisasi data langsung dari node Binance.",
        "dashboard.stats": "STATISTIK KUANTUM",
        "dashboard.wallet": "Portofolio Futures Aktif",
        "dashboard.pnl": "PNL 24 jam",
        "dashboard.wall": "Dinding Likuiditas Interaktif",
        "projects.title": "KARYA PILIHAN",
        "projects.all": "Semua",
        "projects.web": "Web",
        "projects.mobile": "Mobile",
        "projects.design": "Desain",
        "projects.expand": "LIHAT DETAIL",
        "projects.gallery": "Galeri Foto",
        "projects.close": "Tutup",
        "projects.launch": "Buka Modul",
        "project.project-1.title": "Vibe Commerce",
        "project.project-1.desc": "Mesin e-commerce performa tinggi dengan inventaris real-time dan UI glassmorphism.",
        "project.project-2.title": "Nebula Dashboard",
        "project.project-2.desc": "Dasbor analitik untuk pemantauan cloud dengan grafik interaktif.",
        "project.project-4.title": "Aura Design System",
        "project.project-4.desc": "Sistem desain premium untuk membangun aplikasi web modern.",
        "showcase.title": "Arsitektur",
        "showcase.subtitle": "Terdesentralisasi",
        "showcase.desc": "Membangun kontrak pintar performa tinggi, protokol DeFi, dan algoritma perdagangan kuantitatif prediktif untuk masa depan.",
        "showcase.card1.title": "Web3 Tingkat Institusi",
        "showcase.card1.desc": "Mengembangkan kontrak pintar yang aman dan diaudit untuk volume transaksi besar.",
        "showcase.card1.cta": "Lihat Audit Keamanan",
        "showcase.metric1": "Kontrak Pintar Berjalan",
        "showcase.metric2": "Total Volume Dikelola",
        "showcase.metric3": "ROI Algoritma (YTD)",
        "showcase.metric4": "Protokol DeFi Aktif",
        "quantum.title": "MATRIKS ARBITRASE",
        "quantum.subtitle": "HFT KUANTUM",
        "quantum.desc": "Visualisasi Real-Time Bot Trading Algoritmik. Simulasi deteksi harga DEX, Flash Loan, dan eksekusi profit.",
        "quantum.execute": "Eksekusi Simulator",
        "quantum.simulating": "Mensimulasikan...",
        "quantum.est_profit": "Estimasi Profit (USDC)",
        "admin.title": "VIBE",
        "admin.subtitle": "KONSOL",
        "admin.overview": "Ringkasan",
        "admin.content": "Editor Konten",
        "admin.media": "Manajer Media",
        "admin.exit": "Keluar Konsol",
        "contact.email": "bagusnetagain@gmail.com",
        "contact.github": "https://github.com/ravel-iska",
        "contact.instagram": "https://www.instagram.com/og.0xbgyz?igsh=MXh5aGZnOXBtZTBqZQ==",
        "contact.wa": "https://wa.me/6281234567890",
        "chat.persona": "Anda adalah Vibe AI, asisten pribadi Bagus Priambudi. Bagus adalah lulusan IT (Data Analysis), ahli Web3, Programmer, dan Smart Contract Architect. Jika ditanya kontak, berikan Email: bagusnetagain@gmail.com atau Instagram: @og.0xbgyz.",
        "footer.greet": "Punya proyek menarik?",
        "footer.subgreet": "Ayo bangun keajaiban bersama.",
        "footer.cta": "Mulai Proyek",
        "footer.copyright": "DIRANCANG DENGAN NEXT.JS & PERFORMA TINGGI."
    },
    EN: {
        "nav.home": "Home",
        "nav.about": "About",
        "nav.projects": "Projects",
        "nav.memories": "Memories",
        "nav.dashboard": "Vibe Dashboard",
        "nav.admin": "Admin Console",
        "nav.cv": "Curriculum Vitae",
        "nav.contact": "Contact",
        "hero.role": "IT Data Analyst, Web3 Programmer, Vibe AI Specialist, & Smart Contract Architect.",
        "hero.desc": "Designing predictive data architectures and building the decentralized innovations of tomorrow.",
        "hero.cta": "Explore Work",
        "about.title": "ABOUT ME",
        "about.desc1": "I am Bagus Priambudi, an IT graduate with a concentration in Data Analysis. I have developed a deep passion for Web3 architecture and Algorithmic Trading. My vision is to merge secure systems with stunningly beautiful interfaces.",
        "about.desc2": "I specialize in building advanced Vibe Dashboards, where every data point is rendered with unparallelled visual precision. I'm not merely a participant in the digital ecosystem - I am an innovator hungry to learn.",
        "about.role": "BRIDGING DATA & WEB3 TECHNOLOGY",
        "timeline.title": "JOURNAL OF MY EVOLUTION",
        "timeline.subtitle": "CLICK CARDS TO EXPAND DETAILS",
        "timeline.m1.title": "PRIMARY & SECONDARY SCHOOL",
        "timeline.m1.label": "LOGIC FOUNDATIONS",
        "timeline.m1.details": "Building an initial interest in logic, problem-solving, and analytical thinking.",
        "timeline.m2.title": "VOCATIONAL SCHOOL (SMK/SMA)",
        "timeline.m2.label": "BASIC PROGRAMMING",
        "timeline.m2.details": "Beginning to explore algorithms, basic data structures, and hands-on code logic assembly.",
        "timeline.m3.title": "COLLEGE (UNIVERSITY)",
        "timeline.m3.label": "ADVANCED COMPUTER SCIENCE",
        "timeline.m3.details": "In-depth exploration of Database Architecture, Software Engineering, and Computer Networking.",
        "timeline.m4.title": "BOOTCAMP & CERTIFICATIONS",
        "timeline.m4.label": "WEB3 & AI SPECIALIZATION",
        "timeline.m4.details": "Intensive training focusing on Modern Fullstack projects, Web3, and Artificial Intelligence integration.",
        "timeline.m5.title": "PROFESSIONAL WORLD",
        "timeline.m5.label": "REAL WORLD IMPLEMENTATION",
        "timeline.m5.details": "Full immersion into the software industry, developing large-scale systems used by tens of thousands of clients.",
        "chat.title": "VIBE A.I. AGENT",
        "chat.ready": "AGENT READY FOR BACKEND IMPLEMENTATION",
        "chat.intro": "Hello! I am the Vibe AI Agent, Bagus Priambudi's personal intelligent assistant. How can I assist you with Web3, Data Analysis, or this portfolio?",
        "chat.command": "Execute command...",
        "chat.sim": "[Simulation]: I am not currently connected to the backend by Bagus.",
        "dashboard.title": "DEFI ARCHITECTURE",
        "dashboard.role": "SMART CONTRACT ARCHITECT",
        "dashboard.desc": "Navigating Web3 infrastructure, combining extreme cryptographic security with decentralized system efficiency. Live data pipeline synced directly from Binance node.",
        "dashboard.stats": "QUANTUM STATS",
        "dashboard.wallet": "Active Futures Portfolio",
        "dashboard.pnl": "24h PNL",
        "dashboard.wall": "Interactive Liquidity Wall",
        "projects.title": "SELECTED WORKS",
        "projects.all": "All",
        "projects.web": "Web",
        "projects.mobile": "Mobile",
        "projects.design": "Design",
        "projects.expand": "EXPAND ARTIFACT",
        "projects.gallery": "Photo Gallery",
        "projects.close": "Close",
        "projects.launch": "Launch Module",
        "project.project-1.title": "Vibe Commerce",
        "project.project-1.desc": "High-performance e-commerce engine with real-time inventory and glassmorphism UI.",
        "project.project-2.title": "Nebula Dashboard",
        "project.project-2.desc": "Analytical dashboard for cloud monitoring with interactive charts.",
        "project.project-4.title": "Aura Design System",
        "project.project-4.desc": "A premium design system for building modern web applications.",
        "showcase.title": "Architecture",
        "showcase.subtitle": "Decentralized",
        "showcase.desc": "Engineering high-performance smart contracts, DeFi protocols, and predictive quantitative trading algorithms for the next generation of the web.",
        "showcase.card1.title": "Institutional-Grade Web3",
        "showcase.card1.desc": "Developing secure, audited smart contracts capable of processing millions in daily volume.",
        "showcase.card1.cta": "View Security Audits",
        "showcase.metric1": "Smart Contracts Deployed",
        "showcase.metric2": "Total Volume Handled",
        "showcase.metric3": "Algorithmic ROI (YTD)",
        "showcase.metric4": "Active DeFi Protocols",
        "quantum.title": "ARBITRAGE MATRIX",
        "quantum.subtitle": "QUANTUM HFT",
        "quantum.desc": "Real-Time Visualization of Algorithmic Trading Bot. Simulating DEX price detection, Flash Loan, and profit execution.",
        "quantum.execute": "Execute Simulator",
        "quantum.simulating": "Simulating...",
        "quantum.est_profit": "Est. Profit (USDC)",
        "admin.title": "VIBE",
        "admin.subtitle": "CONSOLE",
        "admin.overview": "Overview",
        "admin.content": "Content Editor",
        "admin.media": "Media Manager",
        "admin.exit": "Exit Console",
        "contact.email": "bagusnetagain@gmail.com",
        "contact.github": "https://github.com/ravel-iska",
        "contact.instagram": "https://www.instagram.com/og.0xbgyz?igsh=MXh5aGZnOXBtZTBqZQ==",
        "contact.wa": "https://wa.me/6281234567890",
        "chat.persona": "You are Vibe AI, personal assistant for Bagus Priambudi. Bagus is an IT Graduate (Data Analysis), Web3 Expert, Programmer, and Smart Contract Architect. If asked for contact, provide Email: bagusnetagain@gmail.com or Instagram: @og.0xbgyz."
    },
    JP: {
        "nav.home": "ホーム",
        "nav.about": "約",
        "nav.projects": "プロジェクト",
        "nav.memories": "思い出",
        "nav.dashboard": "Vibeダッシュボード",
        "nav.admin": "管理コンソール",
        "nav.cv": "履歴書",
        "nav.contact": "連絡先",
        "hero.role": "ITデータアナリスト | Web3プログラマー | Vibe AI | スマートコントラクトアーキテクト",
        "hero.desc": "予測データ アーキテクチャを設計し、未来の分散型イノベーションを構築します。",
        "hero.cta": "作品を見る",
        "about.title": "私について",
        "about.desc1": "私はBagus Priambudi（バグース・プリアンブディ）です。データ分析を専攻したIT卒業生です。Web3アーキテクチャとアルゴリズム取引に深い情熱を持っています。安全なシステムと美しいインターフェースを融合させるのが私のビジョンです。",
        "about.desc2": "私は高度なVibeダッシュボードの構築を専門としています。すべてのデータポイントが比類のない視覚的精度でレンダリングされます。",
        "about.role": "データとWeb3テクノロジーの架け橋",
        "timeline.title": "私の進化のジャーナル",
        "timeline.subtitle": "カードをクリックして詳細を表示",
        "timeline.m1.title": "小・中学校",
        "timeline.m1.label": "論理の基礎",
        "timeline.m1.details": "論理、問題解決、分析的思考への初期の関心を構築。",
        "timeline.m2.title": "専門学校（SMK / SMA）",
        "timeline.m2.label": "基本的なプログラミング",
        "timeline.m2.details": "アルゴリズム、基本的なデータ構造、および実践的なコード ロジック アセンブリの探索を開始。",
        "timeline.m3.title": "大学",
        "timeline.m3.label": "高度なコンピュータサイエンス",
        "timeline.m3.details": "データベース アーキテクチャ、ソフトウェア エンジニアリング、およびコンピュータ ネットワークの詳細な調査。",
        "timeline.m4.title": "ブートキャンプと認定",
        "timeline.m4.label": "WEB3とAIの専門化",
        "timeline.m4.details": "最新のフルスタック プロジェクト、Web3、および人工知能の統合に焦点を当てた集中トレーニング。",
        "timeline.m5.title": "プロの世界",
        "timeline.m5.label": "現実世界の実装",
        "timeline.m5.details": "ソフトウェア業界に完全に没頭し、数万のクライアントが使用する大規模システムを開発。",
        "chat.title": "VIBE A.I. エージェント",
        "chat.ready": "バックエンド実装の準備ができました",
        "chat.intro": "こんにちは！私はVibe AI Agent、Bagus Priambudiの個人アシスタントです。お手伝いしましょうか？",
        "chat.command": "コマンドを実行...",
        "chat.sim": "[シミュレーション]: 現在バックエンドに接続されていません。",
        "dashboard.title": "DeFi アーキテクチャ",
        "dashboard.role": "スマートコントラクトアーキテクト",
        "dashboard.desc": "極端な暗号セキュリティと分散システム効率を組み合わせたWeb3インフラストラクチャのナビゲート。Binanceノードから直接同期されたライブデータパイプライン。",
        "dashboard.stats": "量子統計",
        "dashboard.wallet": "アクティブな先物ポートフォリオ",
        "dashboard.pnl": "24時間損益",
        "dashboard.wall": "対話型流動性の壁",
        "projects.title": "厳選された作品",
        "projects.all": "すべて",
        "projects.web": "ウェブ",
        "projects.mobile": "モバイル",
        "projects.design": "デザイン",
        "projects.expand": "アーティファクトを展開",
        "projects.gallery": "フォトギャラリー",
        "projects.close": "閉じる",
        "projects.launch": "モジュールを起動",
        "project.project-1.title": "Vibe Commerce",
        "project.project-1.desc": "リアルタイムの在庫管理とグラスモーフィズムUIを備えた高性能eコマースエンジン。",
        "project.project-2.title": "Nebula Dashboard",
        "project.project-2.desc": "インタラクティブなチャートを備えたクラウド監視用分析ダッシュボード。",
        "project.project-4.title": "Aura Design System",
        "project.project-4.desc": "最新のウェブアプリケーションを構築するためのプレミアムデザインシステム。",
        "showcase.title": "アーキテクチャ",
        "showcase.subtitle": "分散型",
        "showcase.desc": "次世代のウェブに向けた高性能スマートコントラクト、DeFiプロトコル、および予測定量的取引アルゴリズムのエンジニアリング。",
        "showcase.card1.title": "機関グレードのWeb3",
        "showcase.card1.desc": "数百万の1日取引量を処理できる、安全で監査済みのスマートコントラクトの開発。",
        "showcase.card1.cta": "セキュリティ監査を表示",
        "showcase.metric1": "展開済みのスマートコントラクト",
        "showcase.metric2": "総処理ボリューム",
        "showcase.metric3": "アルゴリズムROI (YTD)",
        "showcase.metric4": "アクティブなDeFiプロトコル",
        "quantum.title": "アービトラージマトリックス",
        "quantum.subtitle": "クォンタム HFT",
        "quantum.desc": "アルゴリズム取引ボットのリアルタイム視覚化。DEX価格検出、フラッシュローン、および利益実行のシミュレーション。",
        "quantum.execute": "シミュレーターを実行",
        "quantum.simulating": "シミュレーション中...",
        "quantum.est_profit": "推定利益 (USDC)",
        "admin.title": "VIBE",
        "admin.subtitle": "コンソール",
        "admin.overview": "概要",
        "admin.content": "コンテンツエディタ",
        "admin.media": "メディアマネージャー",
        "admin.exit": "コンソールを終了"
    },
    ZH: {
        "nav.home": "首页",
        "nav.about": "关于",
        "nav.projects": "项目",
        "nav.memories": "回忆录",
        "nav.dashboard": "Vibe 仪表板",
        "nav.admin": "管理控制台",
        "nav.cv": "履历",
        "nav.contact": "联系方式",
        "hero.role": "IT数据分析师 | Web3程序员 | Vibe AI | 智能合约架构师",
        "hero.desc": "设计预测性数据架构并构建未来的去中心化创新。",
        "hero.cta": "探索作品",
        "about.title": "关于我",
        "about.desc1": "我是 Bagus Priambudi，一名专注于数据分析的IT毕业生。我对Web3架构和算法交易有着浓厚的兴趣。我的愿景是将安全的系统与极具美感的界面融为一体。",
        "about.desc2": "我专注于构建高级Vibe仪表板，将每个数据点以无与伦比的视觉精度呈现出来。我不仅仅是数字生态系统的参与者——我是一个渴望学习的创新者。",
        "about.role": "连接数据与 Web3 技术",
        "timeline.title": "我的进化日志",
        "timeline.subtitle": "点击卡片展开详情",
        "timeline.m1.title": "小学及中学",
        "timeline.m1.label": "逻辑基础",
        "timeline.m1.details": "建立对逻辑、解决问题和分析思维的初步兴趣。",
        "timeline.m2.title": "职业高中 (SMK/SMA)",
        "timeline.m2.label": "基础编程",
        "timeline.m2.details": "开始深入研究算法、基础数据结构以及动手编写代码逻辑。",
        "timeline.m3.title": "大学",
        "timeline.m3.label": "高级计算机科学",
        "timeline.m3.details": "深入探索数据库架构、软件工程和计算机网络。",
        "timeline.m4.title": "训练营与认证",
        "timeline.m4.label": "Web3与人工智能专业化",
        "timeline.m4.details": "针对现代全栈项目、Web3和人工智能集成的强化培训。",
        "timeline.m5.title": "职业生涯",
        "timeline.m5.label": "现实世界落地",
        "timeline.m5.details": "全身心投入软件行业，开发供数万客户使用的大规模系统。",
        "chat.title": "VIBE A.I. 代理",
        "chat.ready": "代理已准备好进行后端实现",
        "chat.intro": "你好！我是Vibe AI智能助理，Bagus Priambudi的私人助手。我能帮你了解Web3、数据分析或本作品集吗？",
        "chat.command": "执行命令...",
        "chat.sim": "[模拟]: 目前我尚未连接到后端。",
        "dashboard.title": "DeFi 架构",
        "dashboard.role": "智能合约架构师",
        "dashboard.desc": "导航 Web3 基础设施，将极限密码安全与去中心化系统效率相结合。直接从币安节点同步实时数据。",
        "dashboard.stats": "量子统计",
        "dashboard.wallet": "活跃期货投资组合",
        "dashboard.pnl": "24小时盈亏",
        "dashboard.wall": "互动流动性墙",
        "projects.title": "精品项目",
        "projects.all": "全部",
        "projects.web": "网页",
        "projects.mobile": "移动端",
        "projects.design": "设计",
        "projects.expand": "展开详情",
        "projects.gallery": "照片画廊",
        "projects.close": "关闭",
        "projects.launch": "启动模块",
        "project.project-1.title": "Vibe 商城",
        "project.project-1.desc": "具有实时库存和毛玻璃UI的高性能电子商务引擎。",
        "project.project-2.title": "Nebula 仪表板",
        "project.project-2.desc": "用于云监控的分析仪表板，具有交互式图表。",
        "project.project-4.title": "Aura 设计系统",
        "project.project-4.desc": "用于构建现代 Web 应用程序的高级设计系统。",
        "showcase.title": "架构",
        "showcase.subtitle": "去中心化",
        "showcase.desc": "为下一代互联网设计高性能智能合约、DeFi 协议和预测性量化交易算法。",
        "showcase.card1.title": "机构级 Web3",
        "showcase.card1.desc": "开发安全、经过审计且能够处理每日数百万交易量的智能合约。",
        "showcase.card1.cta": "查看安全审计",
        "showcase.metric1": "已部署智能合约",
        "showcase.metric2": "总处理量",
        "showcase.metric3": "算法投资回报率 (YTD)",
        "showcase.metric4": "活跃 DeFi 协议",
        "quantum.title": "套利矩阵",
        "quantum.subtitle": "量子 HFT",
        "quantum.desc": "算法交易机器人的实时可视化。模拟 DEX 价格检测、闪电贷和利润执行。",
        "quantum.execute": "执行模拟器",
        "quantum.simulating": "正在模拟...",
        "quantum.est_profit": "预计利润 (USDC)",
        "admin.title": "VIBE",
        "admin.subtitle": "控制台",
        "admin.overview": "概览",
        "admin.content": "内容编辑器",
        "admin.media": "媒体管理器",
        "admin.exit": "退出控制台"
    },
    RU: {
        "nav.home": "Главная",
        "nav.about": "Обо мне",
        "nav.projects": "Проекты",
        "nav.memories": "Воспоминания",
        "nav.dashboard": "Панель Vibe",
        "nav.admin": "Консоль админа",
        "nav.cv": "Резюме",
        "nav.contact": "Контакт",
        "hero.role": "ИТ-аналитик | Web3-программист | ИИ Специалист | Архитектор Смарт-контрактов",
        "hero.desc": "Проектирование архитектуры прогнозных данных и создание децентрализованных инноваций будущего.",
        "hero.cta": "Посмотреть проект",
        "about.title": "ОБО МНЕ",
        "about.desc1": "Я Багус Приамбуди, ИТ-специалист, занимающийся анализом данных. У меня глубокая страсть к архитектуре Web3 и алгоритмическому трейдингу. Моя цель — соединить безопасные системы с эстетически безупречными интерфейсами.",
        "about.desc2": "Я специализируюсь на создании профессиональных панелей Vibe, где каждая точка данных отображается с невероятной точностью. Я — новатор, жаждущий знаний.",
        "about.role": "СОЕДИНЕНИЕ ДАННЫХ И ТЕХНОЛОГИЙ WEB3",
        "timeline.title": "ЖУРНАЛ МОЕЙ ЭВОЛЮЦИИ",
        "timeline.subtitle": "НАЖМИТЕ НА КАРТУ ДЛЯ ПОДРОБНОСТЕЙ",
        "timeline.m1.title": "ШКОЛА",
        "timeline.m1.label": "ОСНОВЫ ЛОГИКИ",
        "timeline.m1.details": "Формирование раннего интереса к логике, решению задач и аналитическому мышлению.",
        "timeline.m2.title": "ПРОФЕССИОНАЛЬНАЯ ШКОЛА",
        "timeline.m2.label": "ОСНОВЫ ПРОГРАММИРОВАНИЯ",
        "timeline.m2.details": "Изучение алгоритмов, базовых структур данных и практическая сборка программной логики.",
        "timeline.m3.title": "УНИВЕРСИТЕТ",
        "timeline.m3.label": "КОМПЬЮТЕРНЫЕ НАУКИ",
        "timeline.m3.details": "Глубокое изучение архитектуры баз данных, программной инженерии и сетей.",
        "timeline.m4.title": "БУТКЕМПЫ И КУРСЫ",
        "timeline.m4.label": "СПЕЦИАЛИЗАЦИЯ WEB3 И AI",
        "timeline.m4.details": "Интенсивное обучение современным Fullstack проектам, Web3 и интеграции ИИ.",
        "timeline.m5.title": "ПРОФЕССИОНАЛЬНЫЙ ОПЫТ",
        "timeline.m5.label": "РЕАЛЬНОЕ ВНЕДРЕНИЕ",
        "timeline.m5.details": "Полное погружение в ИТ-индустрию, разработка масштабных систем для тысяч пользователей.",
        "chat.title": "VIBE A.I. АГЕНТ",
        "chat.ready": "АГЕНТ ГОТОВ К ИНТЕГРАЦИИ",
        "chat.intro": "Привет! Я ИИ-ассистент Багуса Приамбуди. Чем могу помочь?",
        "chat.command": "Выполнить команду...",
        "chat.sim": "[Симуляция]: В данный момент я не подключен к серверу.",
        "dashboard.title": "АРХИТЕКТУРА DEFI",
        "dashboard.role": "АРХИТЕКТОР СМАРТ-КОНТРАКТОВ",
        "dashboard.desc": "Работа с инфраструктурой Web3, объединяющая криптографическую безопасность с высокой производительностью распределенных систем. Данные напрямую с нод Binance.",
        "dashboard.stats": "КВАНТОВАЯ СТАТИСТИКА",
        "dashboard.wallet": "Активный фьючерсный портфель",
        "dashboard.pnl": "PNL за 24 часа",
        "dashboard.wall": "Стена ликвидности",
        "projects.title": "ЛУЧШИЕ РАБОТЫ",
        "projects.all": "Все",
        "projects.web": "Веб",
        "projects.mobile": "Мобильные",
        "projects.design": "Дизайн",
        "projects.expand": "РАЗВЕРНУТЬ",
        "projects.gallery": "Фотогалерея",
        "projects.close": "Закрыть",
        "projects.launch": "Запустить",
        "project.project-1.title": "Vibe Commerce",
        "project.project-1.desc": "Высокопроизводительный движок e-commerce с инвентаризацией в реальном времени.",
        "project.project-2.title": "Nebula Dashboard",
        "project.project-2.desc": "Аналитическая панель для мониторинга облаков с графиками.",
        "project.project-4.title": "Aura Design System",
        "project.project-4.desc": "Премиальная дизайн-система для современных веб-приложений.",
        "showcase.title": "Архитектура",
        "showcase.subtitle": "Децентрализованная",
        "showcase.desc": "Разработка высокопроизводительных смарт-контрактов, протоколов DeFi и прогнозных количественных алгоритмов торговли для веба следующего поколения.",
        "showcase.card1.title": "Web3 институционального уровня",
        "showcase.card1.desc": "Разработка безопасных, проверенных смарт-контрактов, способных обрабатывать миллионные ежедневные объемы.",
        "showcase.card1.cta": "Просмотреть аудит безопасности",
        "showcase.metric1": "Развернуто смарт-контрактов",
        "showcase.metric2": "Общий объем обработки",
        "showcase.metric3": "ROI алгоритма (YTD)",
        "showcase.metric4": "Активные протоколы DeFi",
        "quantum.title": "МАТРИЦА АРБИТРАЖА",
        "quantum.subtitle": "КВАНТОВЫЙ HFT",
        "quantum.desc": "Визуализация торгового бота в реальном времени. Симуляция обнаружения цен на DEX, Flash Loan и получения прибыли.",
        "quantum.execute": "Запустить симулятор",
        "quantum.simulating": "Симуляция...",
        "quantum.est_profit": "Ожидаемая прибыль (USDC)",
        "admin.title": "VIBE",
        "admin.subtitle": "КОНСОЛЬ",
        "admin.overview": "Обзор",
        "admin.content": "Редактор контента",
        "admin.media": "Менеджер медиа",
        "admin.exit": "Выйти из консоли",
        "footer.greet": "Есть проект на примете?",
        "footer.subgreet": "Давайте творить магию вместе.",
        "footer.cta": "Начать проект",
        "footer.copyright": "СОЗДАНО С NEXT.JS И ЗАБОТОЙ О ПРОИЗВОДИТЕЛЬНОСТИ."
    }
};

const GlobalContext = createContext<GlobalState | null>(null);

export function GlobalProvider({ children }: { children: React.ReactNode }) {
    const [theme, setTheme] = useState<Theme>("dark");
    const [language, setLanguage] = useState<Language>("ID");
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
    }, []);

    useEffect(() => {
        if (!mounted) return;
        // Sync theme with body for filter compatibility
        if (theme === "light") {
            document.body.classList.add("light-mode");
        } else {
            document.body.classList.remove("light-mode");
        }
    }, [theme, mounted]);

    const toggleTheme = () => {
        setTheme(prev => prev === "dark" ? "light" : "dark");
    };

    const t = (key: string) => {
        if (typeof window !== "undefined") {
            if (key === "hero.role" && localStorage.getItem("vibe_hero_role")) {
                return localStorage.getItem("vibe_hero_role") as string;
            }
            if (key === "about.desc" && localStorage.getItem("vibe_about_desc")) {
                return localStorage.getItem("vibe_about_desc") as string;
            }
        }
        // @ts-ignore
        return dictionaries[language][key] || key;
    };

    if (!mounted) {
        return (
            <GlobalContext.Provider value={{ theme: "dark", toggleTheme, language: "ID", setLanguage, t }}>
                <div id="theme-wrapper" className="min-h-screen">
                    {children}
                </div>
            </GlobalContext.Provider>
        );
    }

    return (
        <GlobalContext.Provider value={{ theme, toggleTheme, language, setLanguage, t }}>
            <div id="theme-wrapper" className="min-h-screen transition-all duration-700 ease-in-out">
                {children}
            </div>
        </GlobalContext.Provider>
    );
}

export function useGlobal() {
    const context = useContext(GlobalContext);
    if (!context) throw new Error("useGlobal must be used within GlobalProvider");
    return context;
}
